"""Command-line interface for local Claim Polygraph NG investigations."""

import argparse
import asyncio
import os
import sys
from collections.abc import Sequence
from pathlib import Path
from uuid import UUID

from claim_polygraph_ng.application import InvestigationService
from claim_polygraph_ng.domain import InvestigationStatus
from claim_polygraph_ng.persistence import SQLiteInvestigationRepository
from claim_polygraph_ng.providers import (
    DeterministicModelProvider,
    DeterministicSearchProvider,
    SearXNGSearchProvider,
)
from claim_polygraph_ng.reporting import export_report, load_report, render_markdown
from claim_polygraph_ng.retrieval import SafeHttpFetcher

DEFAULT_DATABASE = Path("data") / "claim_polygraph_ng.sqlite3"
DEFAULT_ARTIFACTS = Path("artifacts")


def build_parser() -> argparse.ArgumentParser:
    """Build the public command hierarchy."""
    parser = argparse.ArgumentParser(
        prog="claim-polygraph",
        description="Run and inspect local evidence investigations.",
    )
    parser.add_argument(
        "--database",
        type=Path,
        default=DEFAULT_DATABASE,
        help=f"SQLite database path (default: {DEFAULT_DATABASE}).",
    )
    parser.add_argument(
        "--artifacts",
        type=Path,
        default=DEFAULT_ARTIFACTS,
        help=f"Report output directory (default: {DEFAULT_ARTIFACTS}).",
    )
    parser.add_argument(
        "--searxng-url",
        default=os.getenv("SEARXNG_BASE_URL"),
        help=(
            "Opt into real search through this trusted SearXNG base URL. "
            "Can also be set with SEARXNG_BASE_URL."
        ),
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    investigate = subparsers.add_parser(
        "investigate",
        help="Run a local investigation.",
    )
    investigate.add_argument("claim", help="Factual claim to investigate.")

    subparsers.add_parser("list", help="List stored investigations.")

    show = subparsers.add_parser(
        "show",
        help="Render a stored investigation.",
    )
    show.add_argument("investigation_id", help="Investigation UUID.")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Run a CLI command and return a process exit code."""
    args = build_parser().parse_args(argv)
    repository = _repository(args.database)

    try:
        if args.command == "investigate":
            return _investigate(
                repository,
                args.artifacts,
                args.claim,
                args.searxng_url,
            )
        if args.command == "list":
            return _list(repository)
        if args.command == "show":
            return _show(repository, args.artifacts, args.investigation_id)
    except (LookupError, RuntimeError, ValueError) as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1

    raise RuntimeError(f"unsupported command: {args.command}")


def _repository(database: Path) -> SQLiteInvestigationRepository:
    database.parent.mkdir(parents=True, exist_ok=True)
    repository = SQLiteInvestigationRepository(database)
    repository.initialize()
    return repository


def _investigate(
    repository: SQLiteInvestigationRepository,
    artifacts: Path,
    claim: str,
    searxng_url: str | None,
) -> int:
    if searxng_url:
        search_provider = SearXNGSearchProvider(searxng_url)
        content_fetcher = SafeHttpFetcher()
        development_message = (
            "Retrieval mode: real SearXNG search and safe public-page fetching; "
            "claim analysis and judgment remain deterministic."
        )
    else:
        search_provider = DeterministicSearchProvider()
        content_fetcher = None
        development_message = (
            "Development mode: evidence was generated by deterministic mock providers."
        )

    service = InvestigationService(
        repository=repository,
        model_provider=DeterministicModelProvider(),
        search_provider=search_provider,
        content_fetcher=content_fetcher,
    )
    report = asyncio.run(service.investigate(claim))
    events = repository.list_events(report.investigation.investigation_id)
    exported = export_report(report, events, artifacts)

    print(f"Investigation ID: {report.investigation.investigation_id}")
    print(f"Status: {report.investigation.status.value}")
    print(f"Verdict: {report.verdict.label.value}")
    print(f"Report: {exported.report_markdown}")
    print(development_message)
    return 0


def _list(repository: SQLiteInvestigationRepository) -> int:
    investigations = repository.list_investigations()
    if not investigations:
        print("No investigations found.")
        return 0

    print("ID                                   STATUS      STAGE             CLAIM")
    for investigation in investigations:
        claim = investigation.input_claim.replace("\n", " ")
        if len(claim) > 60:
            claim = claim[:57] + "..."
        print(
            f"{investigation.investigation_id} "
            f"{investigation.status.value:<11} "
            f"{investigation.stage.value:<17} "
            f"{claim}"
        )
    return 0


def _show(
    repository: SQLiteInvestigationRepository,
    artifacts: Path,
    raw_investigation_id: str,
) -> int:
    investigation_id = UUID(raw_investigation_id)
    investigation = repository.get_investigation(investigation_id)
    if investigation is None:
        raise LookupError(f"investigation not found: {investigation_id}")

    events = repository.list_events(investigation_id)
    if investigation.status is InvestigationStatus.COMPLETED:
        report = load_report(repository, investigation_id)
        export_report(report, events, artifacts)
        print(render_markdown(report, events), end="")
        return 0

    print(f"Investigation ID: {investigation.investigation_id}")
    print(f"Status: {investigation.status.value}")
    print(f"Stage: {investigation.stage.value}")
    if investigation.failure_reason:
        print(f"Failure: {investigation.failure_reason}")
    print(f"Trace events: {len(events)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
